spring:
  datasource:
    url: >-
      jdbc:mysql://localhost:3306/cherry
      ?useSSL=false
      &allowPublicKeyRetrieval=true
      &serverTimezone=Asia/Seoul
      &characterEncoding=UTF-8
    username: cherry_app
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update

  # Redis Configuration
  data:
    redis:
      host: localhost
      port: 6379
